### ISSUE TITLE
Parse crashed java.lang.NullPointerException

### ISSUE THREAD

**Issue by rickyngk** [rickyngk/pal#4]
<a href="https://app.crittercism.com/developers/crash-details/b9c93e404636db9129e7ef77e1889e2e4a26c45d9b7854d0931159fa"> View Crash Report on Crittercism </a> 

 Reported by: owner vnw (owner@vietnamworks.com)

Status: Unresolved

This Crash occured 1 times for 1 users

0 java.lang.RuntimeException: Unable to start receiver com.parse.ParsePushBroadcastReceiver: java.lang.NullPointerException
1   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2502)
2   at android.app.ActivityThread.access$1700(ActivityThread.java:149)
3   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
4   at android.os.Handler.dispatchMessage(Handler.java:122)
5   at android.os.Looper.loop(Looper.java:136)
6   at android.app.ActivityThread.main(ActivityThread.java:5122)
7   at java.lang.reflect.Method.invokeNative(Native Method)
8   at java.lang.reflect.Method.invoke(Method.java:515)
9   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
10  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
11  at dalvik.system.NativeStart.main(Native Method)
12 Caused by: java.lang.NullPointerException
13  at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
14  at org.json.JSONTokener.nextValue(JSONTokener.java:94)
15  at org.json.JSONObject.<init>(JSONObject.java:155)
16  at org.json.JSONObject.<init>(JSONObject.java:172)
17  at com.parse.ParsePushBroadcastReceiver.onPushReceive(ParsePushBroadcastReceiver.java:141)
18  at com.parse.ParsePushBroadcastReceiver.onReceive(ParsePushBroadcastReceiver.java:117)
19  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2487)
20  ... 10 more
21 java.lang.NullPointerException
22  at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
23  at org.json.JSONTokener.nextValue(JSONTokener.java:94)
24  at org.json.JSONObject.<init>(JSONObject.java:155)
25  at org.json.JSONObject.<init>(JSONObject.java:172)
26  at com.parse.ParsePushBroadcastReceiver.onPushReceive(ParsePushBroadcastReceiver.java:141)
27  at com.parse.ParsePushBroadcastReceiver.onReceive(ParsePushBroadcastReceiver.java:117)
28  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2487)
29  at android.app.ActivityThread.access$1700(ActivityThread.java:149)
30  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
31  at android.os.Handler.dispatchMessage(Handler.java:122)
32  at android.os.Looper.loop(Looper.java:136)
33  at android.app.ActivityThread.main(ActivityThread.java:5122)
34  at java.lang.reflect.Method.invokeNative(Native Method)
35  at java.lang.reflect.Method.invoke(Method.java:515)
36  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
37  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
38  at dalvik.system.NativeStart.main(Native Method)

**Comment by rickyngk** [comment]
fixed in 0.1.2
