### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by rickyngk** [rickyngk/pal#5]
<a href="https://app.crittercism.com/developers/crash-details/17e61d5beb58a1d633d0bdd4757b24f161480765fa0946a6743a86ca"> View Crash Report on Crittercism </a> 

 Reported by: owner vnw (owner@vietnamworks.com)

Status: Unresolved in Version: 0__dot__1__dot__1

This Crash occured 3 times for 1 users

0 java.lang.RuntimeException: Unable to start activity ComponentInfo{vietnamworks.com.pal/vietnamworks.com.pal.activities.TimelineActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.firebase.client.AuthData.getUid()' on a null object reference
1   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
2   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
3   at android.app.ActivityThread.-wrap11(ActivityThread.java)
4   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
5   at android.os.Handler.dispatchMessage(Handler.java:102)
6   at android.os.Looper.loop(Looper.java:148)
7   at android.app.ActivityThread.main(ActivityThread.java:5417)
8   at java.lang.reflect.Method.invoke(Native Method)
9   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.firebase.client.AuthData.getUid()' on a null object reference
12  at vietnamworks.com.pal.models.Posts.getUnreadPostsCounterQuery(Posts.java:79)
13  at vietnamworks.com.pal.activities.TimelineActivity.onCreate(TimelineActivity.java:232)
14  at android.app.Activity.performCreate(Activity.java:6237)
15  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
16  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
17  ... 9 more
18 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.firebase.client.AuthData.getUid()' on a null object reference
19  at vietnamworks.com.pal.models.Posts.getUnreadPostsCounterQuery(Posts.java:79)
20  at vietnamworks.com.pal.activities.TimelineActivity.onCreate(TimelineActivity.java:232)
21  at android.app.Activity.performCreate(Activity.java:6237)
22  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
23  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
24  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
25  at android.app.ActivityThread.-wrap11(ActivityThread.java)
26  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
27  at android.os.Handler.dispatchMessage(Handler.java:102)
28  at android.os.Looper.loop(Looper.java:148)
29  at android.app.ActivityThread.main(ActivityThread.java:5417)
30  at java.lang.reflect.Method.invoke(Native Method)
31  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
32  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by rickyngk** [comment]
fixed in 0.1.2
